### ISSUE TITLE
Editors

### ISSUE THREAD

**Issue by jstutters** [jstutters/qsms_computing_class#3]
@fprados Might be worth suggesting some text editors during the first lecture on scripting to spare people trying to do too much in notepad/gedit.  [Microsoft Visual Code](https://code.visualstudio.com/) and [Atom](https://atom.io/) are both free, cross-platform and not too intimidating to get started with.  If there's no time in the scripting sessions I can cover this as an aside in the python sessions.

**Comment by fprados** [comment]
I would say Atom. Could we install in the network?

**Comment by jstutters** [comment]
Atom seems to be agreeable to everyone.  I believe Jon's looking into installing it.
